/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as LocaleRouteRouteImport } from "./routes/$locale/route";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as LocaleIndexRouteImport } from "./routes/$locale/index";
import { Route as ApiReadyRouteImport } from "./routes/api.ready";
import { Route as ApiHealthRouteImport } from "./routes/api.health";
import { Route as ApiHealthAdaptersRouteImport } from "./routes/api.health.adapters";
import { Route as LocaleAuthVerifyEmailRouteImport } from "./routes/$locale/auth/verify-email";
import { Route as LocaleAuthResetPasswordRouteImport } from "./routes/$locale/auth/reset-password";
import { Route as LocaleAuthRegisterRouteImport } from "./routes/$locale/auth/register";
import { Route as LocaleAuthLoginRouteImport } from "./routes/$locale/auth/login";
import { Route as LocaleAuthForgotPasswordRouteImport } from "./routes/$locale/auth/forgot-password";
import { Route as ApiHealthPlatformsPlatformRouteImport } from "./routes/api.health.platforms.$platform";

const LocaleRouteRoute = LocaleRouteRouteImport.update({
  id: "/$locale",
  path: "/$locale",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => LocaleRouteRoute,
} as any);
const ApiReadyRoute = ApiReadyRouteImport.update({
  id: "/api/ready",
  path: "/api/ready",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: "/api/health",
  path: "/api/health",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiHealthAdaptersRoute = ApiHealthAdaptersRouteImport.update({
  id: "/adapters",
  path: "/adapters",
  getParentRoute: () => ApiHealthRoute,
} as any);
const LocaleAuthVerifyEmailRoute = LocaleAuthVerifyEmailRouteImport.update({
  id: "/auth/verify-email",
  path: "/auth/verify-email",
  getParentRoute: () => LocaleRouteRoute,
} as any);
const LocaleAuthResetPasswordRoute = LocaleAuthResetPasswordRouteImport.update({
  id: "/auth/reset-password",
  path: "/auth/reset-password",
  getParentRoute: () => LocaleRouteRoute,
} as any);
const LocaleAuthRegisterRoute = LocaleAuthRegisterRouteImport.update({
  id: "/auth/register",
  path: "/auth/register",
  getParentRoute: () => LocaleRouteRoute,
} as any);
const LocaleAuthLoginRoute = LocaleAuthLoginRouteImport.update({
  id: "/auth/login",
  path: "/auth/login",
  getParentRoute: () => LocaleRouteRoute,
} as any);
const LocaleAuthForgotPasswordRoute = LocaleAuthForgotPasswordRouteImport.update({
  id: "/auth/forgot-password",
  path: "/auth/forgot-password",
  getParentRoute: () => LocaleRouteRoute,
} as any);
const ApiHealthPlatformsPlatformRoute = ApiHealthPlatformsPlatformRouteImport.update({
  id: "/platforms/$platform",
  path: "/platforms/$platform",
  getParentRoute: () => ApiHealthRoute,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/$locale": typeof LocaleRouteRouteWithChildren;
  "/api/health": typeof ApiHealthRouteWithChildren;
  "/api/ready": typeof ApiReadyRoute;
  "/$locale/": typeof LocaleIndexRoute;
  "/$locale/auth/forgot-password": typeof LocaleAuthForgotPasswordRoute;
  "/$locale/auth/login": typeof LocaleAuthLoginRoute;
  "/$locale/auth/register": typeof LocaleAuthRegisterRoute;
  "/$locale/auth/reset-password": typeof LocaleAuthResetPasswordRoute;
  "/$locale/auth/verify-email": typeof LocaleAuthVerifyEmailRoute;
  "/api/health/adapters": typeof ApiHealthAdaptersRoute;
  "/api/health/platforms/$platform": typeof ApiHealthPlatformsPlatformRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/api/health": typeof ApiHealthRouteWithChildren;
  "/api/ready": typeof ApiReadyRoute;
  "/$locale": typeof LocaleIndexRoute;
  "/$locale/auth/forgot-password": typeof LocaleAuthForgotPasswordRoute;
  "/$locale/auth/login": typeof LocaleAuthLoginRoute;
  "/$locale/auth/register": typeof LocaleAuthRegisterRoute;
  "/$locale/auth/reset-password": typeof LocaleAuthResetPasswordRoute;
  "/$locale/auth/verify-email": typeof LocaleAuthVerifyEmailRoute;
  "/api/health/adapters": typeof ApiHealthAdaptersRoute;
  "/api/health/platforms/$platform": typeof ApiHealthPlatformsPlatformRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/$locale": typeof LocaleRouteRouteWithChildren;
  "/api/health": typeof ApiHealthRouteWithChildren;
  "/api/ready": typeof ApiReadyRoute;
  "/$locale/": typeof LocaleIndexRoute;
  "/$locale/auth/forgot-password": typeof LocaleAuthForgotPasswordRoute;
  "/$locale/auth/login": typeof LocaleAuthLoginRoute;
  "/$locale/auth/register": typeof LocaleAuthRegisterRoute;
  "/$locale/auth/reset-password": typeof LocaleAuthResetPasswordRoute;
  "/$locale/auth/verify-email": typeof LocaleAuthVerifyEmailRoute;
  "/api/health/adapters": typeof ApiHealthAdaptersRoute;
  "/api/health/platforms/$platform": typeof ApiHealthPlatformsPlatformRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/$locale"
    | "/api/health"
    | "/api/ready"
    | "/$locale/"
    | "/$locale/auth/forgot-password"
    | "/$locale/auth/login"
    | "/$locale/auth/register"
    | "/$locale/auth/reset-password"
    | "/$locale/auth/verify-email"
    | "/api/health/adapters"
    | "/api/health/platforms/$platform";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/api/health"
    | "/api/ready"
    | "/$locale"
    | "/$locale/auth/forgot-password"
    | "/$locale/auth/login"
    | "/$locale/auth/register"
    | "/$locale/auth/reset-password"
    | "/$locale/auth/verify-email"
    | "/api/health/adapters"
    | "/api/health/platforms/$platform";
  id:
    | "__root__"
    | "/"
    | "/$locale"
    | "/api/health"
    | "/api/ready"
    | "/$locale/"
    | "/$locale/auth/forgot-password"
    | "/$locale/auth/login"
    | "/$locale/auth/register"
    | "/$locale/auth/reset-password"
    | "/$locale/auth/verify-email"
    | "/api/health/adapters"
    | "/api/health/platforms/$platform";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  LocaleRouteRoute: typeof LocaleRouteRouteWithChildren;
  ApiHealthRoute: typeof ApiHealthRouteWithChildren;
  ApiReadyRoute: typeof ApiReadyRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/$locale": {
      id: "/$locale";
      path: "/$locale";
      fullPath: "/$locale";
      preLoaderRoute: typeof LocaleRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/$locale/": {
      id: "/$locale/";
      path: "/";
      fullPath: "/$locale/";
      preLoaderRoute: typeof LocaleIndexRouteImport;
      parentRoute: typeof LocaleRouteRoute;
    };
    "/api/ready": {
      id: "/api/ready";
      path: "/api/ready";
      fullPath: "/api/ready";
      preLoaderRoute: typeof ApiReadyRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/health": {
      id: "/api/health";
      path: "/api/health";
      fullPath: "/api/health";
      preLoaderRoute: typeof ApiHealthRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/health/adapters": {
      id: "/api/health/adapters";
      path: "/adapters";
      fullPath: "/api/health/adapters";
      preLoaderRoute: typeof ApiHealthAdaptersRouteImport;
      parentRoute: typeof ApiHealthRoute;
    };
    "/$locale/auth/verify-email": {
      id: "/$locale/auth/verify-email";
      path: "/auth/verify-email";
      fullPath: "/$locale/auth/verify-email";
      preLoaderRoute: typeof LocaleAuthVerifyEmailRouteImport;
      parentRoute: typeof LocaleRouteRoute;
    };
    "/$locale/auth/reset-password": {
      id: "/$locale/auth/reset-password";
      path: "/auth/reset-password";
      fullPath: "/$locale/auth/reset-password";
      preLoaderRoute: typeof LocaleAuthResetPasswordRouteImport;
      parentRoute: typeof LocaleRouteRoute;
    };
    "/$locale/auth/register": {
      id: "/$locale/auth/register";
      path: "/auth/register";
      fullPath: "/$locale/auth/register";
      preLoaderRoute: typeof LocaleAuthRegisterRouteImport;
      parentRoute: typeof LocaleRouteRoute;
    };
    "/$locale/auth/login": {
      id: "/$locale/auth/login";
      path: "/auth/login";
      fullPath: "/$locale/auth/login";
      preLoaderRoute: typeof LocaleAuthLoginRouteImport;
      parentRoute: typeof LocaleRouteRoute;
    };
    "/$locale/auth/forgot-password": {
      id: "/$locale/auth/forgot-password";
      path: "/auth/forgot-password";
      fullPath: "/$locale/auth/forgot-password";
      preLoaderRoute: typeof LocaleAuthForgotPasswordRouteImport;
      parentRoute: typeof LocaleRouteRoute;
    };
    "/api/health/platforms/$platform": {
      id: "/api/health/platforms/$platform";
      path: "/platforms/$platform";
      fullPath: "/api/health/platforms/$platform";
      preLoaderRoute: typeof ApiHealthPlatformsPlatformRouteImport;
      parentRoute: typeof ApiHealthRoute;
    };
  }
}

interface LocaleRouteRouteChildren {
  LocaleIndexRoute: typeof LocaleIndexRoute;
  LocaleAuthForgotPasswordRoute: typeof LocaleAuthForgotPasswordRoute;
  LocaleAuthLoginRoute: typeof LocaleAuthLoginRoute;
  LocaleAuthRegisterRoute: typeof LocaleAuthRegisterRoute;
  LocaleAuthResetPasswordRoute: typeof LocaleAuthResetPasswordRoute;
  LocaleAuthVerifyEmailRoute: typeof LocaleAuthVerifyEmailRoute;
}

const LocaleRouteRouteChildren: LocaleRouteRouteChildren = {
  LocaleIndexRoute: LocaleIndexRoute,
  LocaleAuthForgotPasswordRoute: LocaleAuthForgotPasswordRoute,
  LocaleAuthLoginRoute: LocaleAuthLoginRoute,
  LocaleAuthRegisterRoute: LocaleAuthRegisterRoute,
  LocaleAuthResetPasswordRoute: LocaleAuthResetPasswordRoute,
  LocaleAuthVerifyEmailRoute: LocaleAuthVerifyEmailRoute,
};

const LocaleRouteRouteWithChildren = LocaleRouteRoute._addFileChildren(LocaleRouteRouteChildren);

interface ApiHealthRouteChildren {
  ApiHealthAdaptersRoute: typeof ApiHealthAdaptersRoute;
  ApiHealthPlatformsPlatformRoute: typeof ApiHealthPlatformsPlatformRoute;
}

const ApiHealthRouteChildren: ApiHealthRouteChildren = {
  ApiHealthAdaptersRoute: ApiHealthAdaptersRoute,
  ApiHealthPlatformsPlatformRoute: ApiHealthPlatformsPlatformRoute,
};

const ApiHealthRouteWithChildren = ApiHealthRoute._addFileChildren(ApiHealthRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRouteRoute: LocaleRouteRouteWithChildren,
  ApiHealthRoute: ApiHealthRouteWithChildren,
  ApiReadyRoute: ApiReadyRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { createStart } from "@tanstack/react-start";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
