import { describe, expect, it } from "vitest";

import * as schema from "../src/schema/index";

describe("database schema exports", () => {
  it("exports all Phase 0 tables", () => {
    expect(Object.keys(schema).sort()).toEqual([
      "agencyPartnerTierEnum",
      "agencyPartners",
      "aiProviderCredentials",
      "aiProviderFailover",
      "aiProviderHealth",
      "aiProviderModels",
      "aiProviderUsage",
      "aiProviders",
      "aiTemplates",
      "aiUsageAggregationDaily",
      "aiUsageAggregationMonthly",
      "aiUsageReports",
      "alertStatusEnum",
      "alertThresholdTypeEnum",
      "alertTimeWindowEnum",
      "alertTriggerHistory",
      "alertTypeEnum",
      "auditLogs",
      "auditTrail",
      "budgetAlerts",
      "budgetPeriodSummaries",
      "businessDomains",
      "connectorSyncHistory",
      "connectorTagMappings",
      "connectorTags",
      "costTierEnum",
      "dataConnectors",
      "domainConnectorAssignments",
      "domainHierarchyCache",
      "featureFlags",
      "i18nStrings",
      "insightConnectors",
      "insights",
      "marketingMetrics",
      "notificationTypeEnum",
      "permissions",
      "platformCredentials",
      "provenanceRecords",
      "providerScopeEnum",
      "providerStatusEnum",
      "reportShares",
      "reportTemplates",
      "reports",
      "rolePermissions",
      "roles",
      "templateDeployments",
      "templateStatusEnum",
      "templateTypeEnum",
      "templateUsageAnalytics",
      "tenantConnectors",
      "tenantFeatureFlags",
      "tenantStatusEnum",
      "tenantTypeEnum",
      "tenants",
      "usageTracking",
      "userRoles",
      "users",
    ]);
  });
});
